#!/bin/sh

C_PORT=`lsof -t -i:3456`

if [ "$1" = "on" ]; then
  if [ "$C_PORT" = "" ]; then
    echo "turn on"
    gitrpg_server.py &
    # gitrpg_server.py # 開発時は末尾の&を消すとログが見れるよ！
  else
    echo "already running"
  fi
elif [ "$1" = "off" ]; then
  if [ "$C_PORT" = "" ]; then
    echo "server is not running"
  else
    echo "turn off"
    kill $C_PORT
  fi
else
  echo "invalid argument" # TODO help表示
fi
